version: 0.2
            
phases:
  install:
    commands:
      - cd web
      - npm install
      - cd ../api
      - npm install
  pre_build:
    commands:
      - cd web
      - ng build
  build:
    commands:
      - cd web
      - aws s3 sync --delete "./dist" "s3://fabbulle" --cache-control max-age=86400 --exclude "*.html"
      - aws s3 sync --delete "./dist" "s3://fabbulle" --cache-control no-cache --exclude "*" --include "*.html"
      - cd ../api
      - serverless deploy